sfc_currentratio:	sfc_currentratio.cpp
	`root-config --cxx --cflags` -o sfc_currentratio sfc_currentratio.cpp `root-config --glibs`

sfc_scancenter:	sfc_scancenter.cpp
	`root-config --cxx --cflags` -o sfc_scancenter sfc_scancenter.cpp `root-config --glibs`